"""Generate a real five-year market snapshot from Yahoo Finance chart data."""

from __future__ import annotations

import json
import math
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from datetime import UTC, date, datetime, time, timedelta
from decimal import Decimal
from pathlib import Path
from statistics import pstdev

TICKERS = ("SPY", "QQQ", "IWM", "DIA")
OUTPUT = Path("frontend/lib/generated-market-snapshot.ts")
TRADING_DAYS = Decimal("252")
MIN_BARS = 2


@dataclass(frozen=True, slots=True)
class Bar:
    timestamp: datetime
    close: Decimal


def main() -> None:
    end = datetime.now(UTC).date()
    start = end - timedelta(days=365 * 5 + 2)
    try:
        snapshots = [_snapshot(ticker, start, end) for ticker in TICKERS]
    except urllib.error.URLError as exc:
        print(
            "Unable to fetch Yahoo Finance chart data. "
            "Check network/proxy access and rerun the command.",
            file=sys.stderr,
        )
        raise SystemExit(1) from exc
    generated_at = datetime.now(UTC).isoformat()
    OUTPUT.write_text(_typescript(generated_at, start, end, snapshots))
    print(f"wrote {OUTPUT} with {len(snapshots)} real five-year market snapshots")


def _snapshot(ticker: str, start: date, end: date) -> dict[str, object]:
    bars = _fetch_bars(ticker, start, end)
    if len(bars) < MIN_BARS:
        msg = f"not enough bars returned for {ticker}"
        raise RuntimeError(msg)
    closes = [bar.close for bar in bars]
    daily_returns = [
        float(closes[index] / closes[index - 1] - 1)
        for index in range(1, len(closes))
    ]
    total_return = closes[-1] / closes[0] - 1
    years = Decimal(len(closes)) / TRADING_DAYS
    cagr = Decimal(str((float(closes[-1] / closes[0]) ** (1 / float(years))) - 1))
    volatility = Decimal(str(pstdev(daily_returns) * math.sqrt(float(TRADING_DAYS))))
    return {
        "symbol": ticker,
        "startDate": bars[0].timestamp.date().isoformat(),
        "endDate": bars[-1].timestamp.date().isoformat(),
        "bars": len(bars),
        "lastClose": _round(closes[-1]),
        "totalReturn": _round(total_return),
        "cagr": _round(cagr),
        "maxDrawdown": _round(_max_drawdown(closes)),
        "realizedVolatility": _round(volatility),
    }


def _fetch_bars(ticker: str, start: date, end: date) -> list[Bar]:
    period1 = int(datetime.combine(start, time.min, tzinfo=UTC).timestamp())
    period2 = int(datetime.combine(end + timedelta(days=1), time.min, tzinfo=UTC).timestamp())
    query = urllib.parse.urlencode(
        {
            "period1": period1,
            "period2": period2,
            "interval": "1d",
            "events": "history",
            "includeAdjustedClose": "true",
        }
    )
    url = f"https://query1.finance.yahoo.com/v8/finance/chart/{ticker}?{query}"
    request = urllib.request.Request(url, headers={"User-Agent": "ai-quant-platform/0.1"})
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.loads(response.read())
    result = payload["chart"]["result"][0]
    timestamps = result["timestamp"]
    closes = result["indicators"]["quote"][0]["close"]
    bars: list[Bar] = []
    for raw_timestamp, close in zip(timestamps, closes, strict=True):
        if close is None:
            continue
        bars.append(
            Bar(
                timestamp=datetime.fromtimestamp(raw_timestamp, tz=UTC),
                close=Decimal(str(close)),
            )
        )
    return bars


def _max_drawdown(closes: list[Decimal]) -> Decimal:
    peak = closes[0]
    max_drawdown = Decimal("0")
    for close in closes:
        peak = max(peak, close)
        drawdown = close / peak - 1
        max_drawdown = min(max_drawdown, drawdown)
    return max_drawdown


def _round(value: Decimal) -> str:
    return str(value.quantize(Decimal("0.0001")))


def _typescript(
    generated_at: str, start: date, end: date, snapshots: list[dict[str, object]]
) -> str:
    requested_range = {"startDate": start.isoformat(), "endDate": end.isoformat()}
    snapshot_json = json.dumps(snapshots, indent=2)
    return (
        "// Generated by scripts/generate_market_snapshot.py from Yahoo Finance chart data.\n"
        "// Do not edit by hand. Regenerate to refresh the historical snapshot.\n\n"
        "export type MarketSnapshot = {\n"
        "  symbol: string;\n  startDate: string;\n  endDate: string;\n  bars: number;\n"
        "  lastClose: string;\n  totalReturn: string;\n  cagr: string;\n"
        "  maxDrawdown: string;\n  realizedVolatility: string;\n};\n\n"
        f"export const marketSnapshotGeneratedAt = {json.dumps(generated_at)};\n"
        f"export const marketSnapshotRequestedRange = {json.dumps(requested_range)};\n"
        f"export const marketSnapshots: MarketSnapshot[] = {snapshot_json};\n"
    )


if __name__ == "__main__":
    main()
