// Generated by scripts/generate_market_snapshot.py from Yahoo Finance chart data.
// Empty by default so the UI never displays synthetic prices.

export type MarketSnapshot = {
  symbol: string;
  startDate: string;
  endDate: string;
  bars: number;
  lastClose: string;
  totalReturn: string;
  cagr: string;
  maxDrawdown: string;
  realizedVolatility: string;
};

export const marketSnapshotGeneratedAt: string | null = null;
export const marketSnapshotRequestedRange = null satisfies { startDate: string; endDate: string } | null;
export const marketSnapshots: MarketSnapshot[] = [];
